### ISSUE TITLE
@module bugado

### ISSUE THREAD

**Issue by mateusavila** [chrisenytc/grunt-roole#1]
Oi Chris

Eu tava estudando o roole, e vi que tinha um bug aqui no grunt, quando eu gero o @module, ele gera um arquivo vazio. to usando junto com o css-min. Tirando isso, o roole funciona maravilhosamente bem.

**Comment by chrisenytc** [comment]
Olá @mateusavila, Obrigado por relatar esse bug. Sobre a criação de arquivos vazios quando um erro era gerado pelo compilador, isso foi corrigido no commit 1e32c8d5f5008a2a701a113e39a616a1853d7d33. Sobre o problema com `@module` você precisa colocar um `ponto` antes do nome do módulo por exemplo `@module .foo`. Se não fizer isso o compilador vai apontar um erro de sintaxe.
