### ISSUE TITLE
grunt-roole gera um arquivo com erro de sintaxe css

### ISSUE THREAD

**Issue by mateusavila** [chrisenytc/grunt-roole#2]
OI

Eu criei um arquivo style.roo, com o seguinte css:
# coisa{background: url("../img/coisa.png");}

porém, executando o grunt, ele gera um arquivo com essa sintaxe:
# coisa{background: url("..\img\coisa.png");}

repare que a barra ficou invertida, como se estivesse escapando alguma coisa. Eu testei tanto com aspas simples e com aspas grossas, e gerou o mesmo resultado.

**Comment by chrisenytc** [comment]
Esse erro não é no plugin. O Roole quando usa url no css precisa de uma base para ser usada no compilador. 

Tente: `#coisa{background: url(http://suaurl/img/coisa.png);}`
ou defina a opção `base` nas opções do plugin.

``` json
options: {
  base: 'http://suaurl/',
}
```
